### ISSUE TITLE
Why not use Double?

### ISSUE THREAD

**Issue by kasbah** [Twinside/svg-tree#1]
I was just wondering about this as I am interfacing [my library](https://github.com/kasbah/haskell-kicad-data) (which uses Double) to yours. I could change my library to use Float which would avoid using float2Double everywhere so I  was wondering why you chose Float over Double? I think [the SVG spec says floats should be double precision](http://www.w3.org/TR/2003/REC-SVG11-20030114/conform.html#ConformingSVGViewers).

**Comment by Twinside** [comment]
> All visual rendering must be accurate to within one device pixel (px unit) to
> the mathematically correct result at the initial 1:1 zoom ratio. It is suggested
> that viewers attempt to keep a high degree of accuracy when zooming.

and

> Both a Conforming High-Quality Static SVG Viewer and a Conforming
> High-Quality Dynamic SVG Viewer must support the following additional
> features:
> ...
> At least double-precision floating point computation on coordinate system
> transformation numerical calculations.

[SkScalar](https://code.google.com/p/skia/source/browse/trunk/include/core/SkScalar.h?r=875) of SKIA, the Chrome rendering library, which use float in it's pipeline.

Simply put, for rendering, float precision is sufficient. Thus said, holding all the geometry and transformation can be put in double, if it can open more use of the library. But changing the type of the drawing attributes hold literally no value.

And what is more problematic for me, it's a **major** change forcing a bump to a 0.3 version, that will force me to update rasterific-svg . I'm willing to accept a patch, if only transformation/geometry is switched to doubles.

**Comment by kasbah** [comment]
What about `_strokeWidth :: Number`? That's a drawing attribute but is it OK to switch that to using Double since all the transformation/geometry uses the Number type as well?

**Comment by Twinside** [comment]
I think we can, let's just keep only the color stuff with Float

**Comment by kasbah** [comment]
So the problem I am running into in making this change as you describe is that the other attributes are tied to Number through the `cssUniqueFloat` and `cssUniqueMayFloat` lenses. I haven't had the time to understand whether these can be decoupled from Number in a nice way.

**Comment by Twinside** [comment]
I've pulled your modifications and switched back the value for opacity, and bumped the revision number. is it good for you?

**Comment by kasbah** [comment]
Yes, perfect, thanks very much! The `ASetter` type and the Lense operators were confusing me.
