### ISSUE TITLE
Are the monoids necessary?

### ISSUE THREAD

**Issue by lemmih** [Twinside/svg-tree#18]
A lot of the draw attributes (such as strokeWidth and strokeColor) use the 'Last' monoid. As I see it, the only purpose of this is to tell when attributes have been omitted. Are there any use-cases that require this or can we simply fill in missing attributes with their default values?

**Comment by Twinside** [comment]
Yes, it is to support simple `DrawAttributes` management in `rasterific-svg`, that use `DrawAttributes`'s monoid instance to propagate current values
