### ISSUE TITLE
Serialization of None values in Trees

### ISSUE THREAD

**Issue by gaa-cifasis** [Twinside/svg-tree#8]
Hi,

We recently discovered that the value None in the Tree datatype is serialized as "< />" and this element is not validated by some XML libraries (for instance libxml2). Such SVG files are rejected by libraries like librsvg2 or Firefox. For instance, [this svg file](https://gist.github.com/gaa-cifasis/50d5a0c0e137cd0a36a4).

This issue was found using QuickFuzz (we have a new engine to generate arbitrary instances in using svg-tree, thanks to @martinceresa ).

**Comment by Twinside** [comment]
Thanks, I'll fix it asap
