### ISSUE TITLE
Id redefination is still possible

### ISSUE THREAD

**Issue by gaa-cifasis** [Twinside/svg-tree#9]
Hi,

Even in the last revision, it is still possible to serialize a svg and obtain an invalid svg because of a duplicated id. For instance:

> Document {_viewBox = Just (10.93378015676586,-2.5002198377193974,1.1076888622404122,1.3056209094151552), _width = Nothing, _height = Nothing, _elements = [], _definitions = fromList [("d",ElementClipPath (ClipPath {_clipPathDrawAttributes = DrawAttributes {_strokeWidth = Last {getLast = Nothing}, _strokeColor = Last {getLast = Just (TextureRef "d")}, _strokeOpacity = Nothing, _strokeLineCap = Last {getLast = Just CapButt}, _strokeLineJoin = Last {getLast = Just JoinMiter}, _strokeMiterLimit = Last {getLast = Just 0.608029056458719}, _fillColor = Last {getLast = Just (TextureRef "a")}, _fillOpacity = Nothing, _groupOpacity = Just (-1.1104697), _transform = Just [], _fillRule = Last {getLast = Nothing}, _maskRef = Last {getLast = Nothing}, _clipPathRef = Last {getLast = Nothing}, _clipRule = Last {getLast = Nothing}, _attrClass = ["b"], _attrId = Just "e", _strokeOffset = Last {getLast = Nothing}, _strokeDashArray = Last {getLast = Nothing}, _fontSize = Last {getLast = Nothing}, _fontFamily = Last {getLast = Just ["e"]}, _fontStyle = Last {getLast = Just FontStyleItalic}, _textAnchor = Last {getLast = Just TextAnchorStart}, _markerStart = Last {getLast = Nothing}, _markerMid = Last {getLast = Nothing}, _markerEnd = Last {getLast = Just (Ref "d")}}, _clipPathUnits = CoordBoundingBox, _clipPathContent = [CircleTree (Circle {_circleDrawAttributes = DrawAttributes {_strokeWidth = Last {getLast = Nothing}, _strokeColor = Last {getLast = Nothing}, _strokeOpacity = Nothing, _strokeLineCap = Last {getLast = Nothing}, _strokeLineJoin = Last {getLast = Nothing}, _strokeMiterLimit = Last {getLast = Nothing}, _fillColor = Last {getLast = Just (TextureRef "c")}, _fillOpacity = Just 0.0, _groupOpacity = Just 0.0, _transform = Just [], _fillRule = Last {getLast = Nothing}, _maskRef = Last {getLast = Nothing}, _clipPathRef = Last {getLast = Just RefNone}, _clipRule = Last {getLast = Just FillNonZero}, _attrClass = [], _attrId = Just "d", _strokeOffset = Last {getLast = Nothing}, _strokeDashArray = Last {getLast = Nothing}, _fontSize = Last {getLast = Just (Num 0.0)}, _fontFamily = Last {getLast = Nothing}, _fontStyle = Last {getLast = Just FontStyleNormal}, _textAnchor = Last {getLast = Just TextAnchorEnd}, _markerStart = Last {getLast = Just (Ref "e")}, _markerMid = Last {getLast = Just RefNone}, _markerEnd = Last {getLast = Just (Ref "a")}}, _circleCenter = (Num 0.0,Point 0.0), _circleRadius = Mm 0.0})]}))], _description = "d", _styleRules = [], _documentLocation = "b"}

I'm not sure if this is a bug in svg-tree.

**Comment by Twinside** [comment]
I need to install your fuzzer

**Comment by gaa-cifasis** [comment]
We just merged the new code for automatic derivation into the master branch. Try to compile it (./install.sh) and let me know if you need something!

**Comment by gaa-cifasis** [comment]
Fixed in 4594827df59f6bc4c558a5120435ef5ca882266e.

**Comment by Twinside** [comment]
\o/
